/*
  LA VINITECA — CATÁLOGO BASE
  Fuente: catálogo de La Viniteca cargado por el usuario.
  - Producto Demo excluido.
  - Precios dudosos se dejan sin valor para consulta.
  - El stock se confirma por WhatsApp.
*/
window.VINITECA_CATALOG = [
  {
    "id": "20-saint-romain-rouge-alain-gras-magnum-2016",
    "sourceId": 20,
    "name": "Saint-Romain Rouge, Alain Gras - MAGNUM 2016",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2016",
    "image": "",
    "price": 532,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "21-alain-gras-saint-romain-rouge-2017",
    "sourceId": 21,
    "name": "Alain Gras Saint-Romain Rouge 2017",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2017",
    "image": "",
    "price": 308,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "22-caparzo-brunello-di-montalcino-docg-2014",
    "sourceId": 22,
    "name": "Caparzo Brunello di Montalcino DOCG 2014",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2014",
    "image": "",
    "price": 363,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "24-vino-blanco-mondavi-woodbridge-sauvignon-blanc",
    "sourceId": 24,
    "name": "Vino blanco Mondavi Woodbridge Sauvignon Blanc",
    "category": "Blancos",
    "winery": "",
    "grape": "Sauvignon Blanc",
    "region": "",
    "country": "",
    "vintage": "",
    "image": "",
    "price": 177,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "26-chateau-beychevelle-grand-vin-saint-julien-2005",
    "sourceId": 26,
    "name": "Chateau Beychevelle Grand Vin Saint Julien 2005",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2005",
    "image": "",
    "price": 1487,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "27-casa-da-passarella-villa-oliveira-touriga-nacional-2009",
    "sourceId": 27,
    "name": "Casa da Passarella Villa Oliveira Touriga Nacional 2009",
    "category": "Tintos",
    "winery": "",
    "grape": "Touriga Nacional",
    "region": "",
    "country": "",
    "vintage": "2009",
    "image": "",
    "price": 395,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "28-seghesio-rockpile-zinfandel-2013",
    "sourceId": 28,
    "name": "Seghesio Rockpile Zinfandel 2013",
    "category": "Tintos",
    "winery": "",
    "grape": "Zinfandel",
    "region": "",
    "country": "",
    "vintage": "2013",
    "image": "",
    "price": 444,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "29-el-porvenir-laborum-de-parcela-malbec-2016",
    "sourceId": 29,
    "name": "El Porvenir Laborum de Parcela Malbec 2016",
    "category": "Tintos",
    "winery": "",
    "grape": "Malbec",
    "region": "",
    "country": "",
    "vintage": "2016",
    "image": "",
    "price": 307,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "30-chateau-du-chatelard-beaujolais-villages-2017",
    "sourceId": 30,
    "name": "Chateau du Chatelard Beaujolais Villages 2017",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2017",
    "image": "",
    "price": 113,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "31-chateau-la-conseillante-pomerol-2006",
    "sourceId": 31,
    "name": "Chateau La Conseillante Pomerol 2006",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2006",
    "image": "",
    "price": 2320,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "33-monte-del-fra-amarone-della-valpolicella-scarnocchio-2011",
    "sourceId": 33,
    "name": "Monte del Fra Amarone della Valpolicella Scarnocchio 2011",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2011",
    "image": "",
    "price": 612,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "34-monte-del-fra-valpolicella-classico-doc-2019",
    "sourceId": 34,
    "name": "Monte del Frà Valpolicella Classico DOC 2019",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2019",
    "image": "",
    "price": 146,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "35-cantina-colli-euganei-notte-di-galileo-riserva-2021",
    "sourceId": 35,
    "name": "Cantina Colli Euganei Notte di Galileo Riserva 2021",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2021",
    "image": "",
    "price": 164,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "36-dominique-piron-morgon-cote-du-py-magnum-2017",
    "sourceId": 36,
    "name": "Dominique Piron Morgon Cote du Py MAGNUM 2017",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2017",
    "image": "",
    "price": 427,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "37-dominique-piron-morgon-cote-du-py-2017",
    "sourceId": 37,
    "name": "Dominique Piron, Morgon Côte du Py 2017",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2017",
    "image": "",
    "price": 214,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "38-domaine-debray-nuits-saint-georges-2011",
    "sourceId": 38,
    "name": "Domaine Debray Nuits Saint Georges 2011",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2011",
    "image": "",
    "price": 259,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "40-el-porvenir-laborum-de-parcela-petit-verdot-2016",
    "sourceId": 40,
    "name": "El Porvenir Laborum de Parcela Petit Verdot 2016",
    "category": "Tintos",
    "winery": "",
    "grape": "Petit Verdot",
    "region": "",
    "country": "",
    "vintage": "2016",
    "image": "",
    "price": 307,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "41-el-porvenir-laborum-de-parcela-tannat-2017",
    "sourceId": 41,
    "name": "El Porvenir Laborum de Parcela Tannat 2017",
    "category": "Tintos",
    "winery": "",
    "grape": "Tannat",
    "region": "",
    "country": "",
    "vintage": "2017",
    "image": "",
    "price": 307,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "42-cuvelier-los-andes-malbec-2015",
    "sourceId": 42,
    "name": "Cuvelier Los Andes Malbec 2015",
    "category": "Tintos",
    "winery": "",
    "grape": "Malbec",
    "region": "",
    "country": "",
    "vintage": "2015",
    "image": "",
    "price": 146,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "43-alvarado-reyes-cabernet-sauvignon",
    "sourceId": 43,
    "name": "Alvarado Reyes Cabernet Sauvignon",
    "category": "Tintos",
    "winery": "",
    "grape": "Cabernet Sauvignon",
    "region": "",
    "country": "",
    "vintage": "",
    "image": "",
    "price": 65,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "44-conde-de-la-conquista-malbec-2022",
    "sourceId": 44,
    "name": "Conde de la Conquista Malbec 2022",
    "category": "Tintos",
    "winery": "",
    "grape": "Malbec",
    "region": "",
    "country": "",
    "vintage": "2022",
    "image": "",
    "price": 615,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "45-clavesana-terra-barbaresco-2016",
    "sourceId": 45,
    "name": "Clavesana Terra Barbaresco 2016",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2016",
    "image": "",
    "price": 205,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "46-perro-negro-cabernet-sauvignon-2022",
    "sourceId": 46,
    "name": "Perro Negro Cabernet Sauvignon 2022",
    "category": "Tintos",
    "winery": "",
    "grape": "Cabernet Sauvignon",
    "region": "",
    "country": "",
    "vintage": "2022",
    "image": "",
    "price": 60,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "47-why-not-blend-2022",
    "sourceId": 47,
    "name": "Why Not Blend 2022",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2022",
    "image": "",
    "price": 70,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "48-raices-negras-cabernet-sauvignon-2022",
    "sourceId": 48,
    "name": "Raices Negras Cabernet Sauvignon 2022",
    "category": "Tintos",
    "winery": "",
    "grape": "Cabernet Sauvignon",
    "region": "",
    "country": "",
    "vintage": "2022",
    "image": "",
    "price": 72,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "49-charsago-negra-criolla-2023",
    "sourceId": 49,
    "name": "Charsago Negra Criolla 2023",
    "category": "Tintos",
    "winery": "",
    "grape": "Negra Criolla",
    "region": "",
    "country": "",
    "vintage": "2023",
    "image": "",
    "price": 56,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "50-hormiga-negra-malbec-2024",
    "sourceId": 50,
    "name": "Hormiga Negra Malbec 2024",
    "category": "Tintos",
    "winery": "",
    "grape": "Malbec",
    "region": "",
    "country": "",
    "vintage": "2024",
    "image": "",
    "price": 35,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "51-quinta-do-portal-grande-reserva-2016",
    "sourceId": 51,
    "name": "Quinta do Portal Grande Reserva 2016",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2016",
    "image": "",
    "price": 294,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "53-cuvelier-los-andes-grand-vin-2015",
    "sourceId": 53,
    "name": "Cuvelier Los Andes Grand Vin 2015",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2015",
    "image": "",
    "price": 274,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "54-chateau-latour-grand-vin-pauillac-1999",
    "sourceId": 54,
    "name": "Chateau Latour Grand Vin Pauillac 1999",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "1999",
    "image": "",
    "price": 6500,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "55-chateau-lafite-rothschild-2010",
    "sourceId": 55,
    "name": "Chateau Lafite Rothschild 2010",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2010",
    "image": "",
    "price": null,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "56-chateau-lynch-bages-2011",
    "sourceId": 56,
    "name": "Chateau Lynch Bages 2011",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2011",
    "image": "",
    "price": 1487,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "57-chateau-l-evangile-2011",
    "sourceId": 57,
    "name": "Chateau L'Evangile 2011",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2011",
    "image": "",
    "price": null,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "58-chateau-l-evangile-2007",
    "sourceId": 58,
    "name": "Chateau L'Evangile 2007",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2007",
    "image": "",
    "price": 1419,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "59-chateau-pichon-longeville-comtesse-de-lalande-grand-cru-2011",
    "sourceId": 59,
    "name": "Chateau Pichon Longeville Comtesse de Lalande Grand Cru 2011",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2011",
    "image": "",
    "price": 1845,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "60-pine-ridge-vineyards-stags-leap-district-2009",
    "sourceId": 60,
    "name": "Pine Ridge Vineyards Stags Leap District 2009",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2009",
    "image": "",
    "price": 499,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "61-chateau-clinet-pomerol-2010",
    "sourceId": 61,
    "name": "Chateau Clinet Pomerol 2010",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2010",
    "image": "",
    "price": 1795,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "62-chateau-penin-natur-2013",
    "sourceId": 62,
    "name": "Chateau Penin Natur 2013",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2013",
    "image": "",
    "price": 133,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "63-maal-wines-biolento-malbec-2017",
    "sourceId": 63,
    "name": "Maal Wines 'Biolento' Malbec 2017",
    "category": "Tintos",
    "winery": "",
    "grape": "Malbec",
    "region": "",
    "country": "",
    "vintage": "2017",
    "image": "",
    "price": 131,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "64-jean-claude-chanudet-beaujolais-villages-la-cuvee-du-chat-2017",
    "sourceId": 64,
    "name": "Jean Claude Chanudet Beaujolais-Villages La Cuvée du Chat 2017",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2017",
    "image": "",
    "price": 208,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "65-jean-claude-chanudet-beaujolais-villages-la-cuvee-du-chat-magnum-2018",
    "sourceId": 65,
    "name": "Jean Claude Chanudet Beaujolais-Villages La Cuvée Du Chat MAGNUM 2018",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2018",
    "image": "",
    "price": 440,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "66-2013-domaine-des-pothiers-cote-roannaise-n-6",
    "sourceId": 66,
    "name": "2013 Domaine Des Pothiers Cote Roannaise N°6",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2013",
    "image": "",
    "price": 114,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "67-sessantanni-primitivo-di-manduria-dop-2019",
    "sourceId": 67,
    "name": "Sessantanni Primitivo di manduria DOP 2019",
    "category": "Tintos",
    "winery": "",
    "grape": "Primitivo",
    "region": "",
    "country": "",
    "vintage": "2019",
    "image": "",
    "price": 284,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "68-il-pumo-primitivo-salento-igp-2022",
    "sourceId": 68,
    "name": "IL Pumo Primitivo Salento IGP 2022",
    "category": "Tintos",
    "winery": "",
    "grape": "Primitivo",
    "region": "",
    "country": "",
    "vintage": "2022",
    "image": "",
    "price": 69,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "69-il-pumo-negroamaro-igp-salento-2023",
    "sourceId": 69,
    "name": "IL Pumo Negroamaro IGP Salento 2023",
    "category": "Tintos",
    "winery": "",
    "grape": "Negroamaro",
    "region": "",
    "country": "",
    "vintage": "2023",
    "image": "",
    "price": 69,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "70-talo-salice-salentino-2021",
    "sourceId": 70,
    "name": "Talò Salice Salentino 2021",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2021",
    "image": "",
    "price": 99,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "71-talo-malvasia-nera-2022",
    "sourceId": 71,
    "name": "Talò Malvasia Nera 2022",
    "category": "Tintos",
    "winery": "",
    "grape": "Malvasia Nera",
    "region": "",
    "country": "",
    "vintage": "2022",
    "image": "",
    "price": 99,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "72-naca-primitivo-puglia-igp-bio-2024",
    "sourceId": 72,
    "name": "Naca Primitivo Puglia IGP Bio 2024",
    "category": "Tintos",
    "winery": "",
    "grape": "Primitivo",
    "region": "",
    "country": "",
    "vintage": "2024",
    "image": "",
    "price": 69,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "73-talo-negroamaro-2023",
    "sourceId": 73,
    "name": "Talò Negroamaro 2023",
    "category": "Tintos",
    "winery": "",
    "grape": "Negroamaro",
    "region": "",
    "country": "",
    "vintage": "2023",
    "image": "",
    "price": 99,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "74-san-marzano-collezione-cinquanta",
    "sourceId": 74,
    "name": "San Marzano Collezione Cinquanta",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "",
    "image": "",
    "price": 229,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "75-talo-primitivo-di-manduria-2022",
    "sourceId": 75,
    "name": "Talò Primitivo di Manduria 2022",
    "category": "Tintos",
    "winery": "",
    "grape": "Primitivo",
    "region": "",
    "country": "",
    "vintage": "2022",
    "image": "",
    "price": 123,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "76-il-pumo-salice-salentino-dop-2021",
    "sourceId": 76,
    "name": "IL Pumo Salice Salentino DOP 2021",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2021",
    "image": "",
    "price": 69,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "77-domodo-montepulciano-d-abruzzo-dop-2021",
    "sourceId": 77,
    "name": "Domodo Montepulciano D’Abruzzo DOP 2021",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2021",
    "image": "",
    "price": 44,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "78-domodo-sangiovese-igp-puglia-2022",
    "sourceId": 78,
    "name": "Domodo Sangiovese IGP Puglia 2022",
    "category": "Tintos",
    "winery": "",
    "grape": "Sangiovese",
    "region": "",
    "country": "",
    "vintage": "2022",
    "image": "",
    "price": 44,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "79-domodo-zinfandel-igp-puglia-2021",
    "sourceId": 79,
    "name": "Domodo Zinfandel IGP Puglia 2021",
    "category": "Tintos",
    "winery": "",
    "grape": "Zinfandel",
    "region": "",
    "country": "",
    "vintage": "2021",
    "image": "",
    "price": 51,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "80-barollo-frater-rosso-2021",
    "sourceId": 80,
    "name": "Barollo Frater Rosso 2021",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2021",
    "image": "",
    "price": 108,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "81-barollo-frank-2020",
    "sourceId": 81,
    "name": "Barollo Frank 2020",
    "category": "Tintos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2020",
    "image": "",
    "price": 223,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "82-alain-gras-saint-romain-blanc-2017",
    "sourceId": 82,
    "name": "Alain Gras Saint-Romain Blanc 2017",
    "category": "Blancos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2017",
    "image": "",
    "price": 308,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "83-alain-gras-saint-romain-blanc-magnum-2016",
    "sourceId": 83,
    "name": "Alain Gras Saint-Romain Blanc, MAGNUM 2016",
    "category": "Blancos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2016",
    "image": "",
    "price": 598,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "84-barollo-sauvignon-blanc-2016",
    "sourceId": 84,
    "name": "Barollo Sauvignon Blanc 2016",
    "category": "Blancos",
    "winery": "",
    "grape": "Sauvignon Blanc",
    "region": "",
    "country": "",
    "vintage": "2016",
    "image": "",
    "price": 96,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "85-cline-cellars-north-coast-viognier-2018",
    "sourceId": 85,
    "name": "Cline Cellars North Coast Viognier 2018",
    "category": "Blancos",
    "winery": "",
    "grape": "Viognier",
    "region": "",
    "country": "",
    "vintage": "2018",
    "image": "",
    "price": 135,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "86-terres-secretes-les-sentinelles-saint-veran-2015",
    "sourceId": 86,
    "name": "Terres Secrètes Les Sentinelles Saint-Véran 2015",
    "category": "Blancos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2015",
    "image": "",
    "price": 164,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "87-mimo-torontel-secano-2017",
    "sourceId": 87,
    "name": "Mimo Torontel Secano 2017",
    "category": "Blancos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2017",
    "image": "",
    "price": 110,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "88-monte-del-fra-ega-garganega-2024",
    "sourceId": 88,
    "name": "Monte del Frà EGA Garganega 2024",
    "category": "Blancos",
    "winery": "",
    "grape": "Garganega",
    "region": "",
    "country": "",
    "vintage": "2024",
    "image": "",
    "price": 114,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "89-monte-del-fra-custoza-2016",
    "sourceId": 89,
    "name": "Monte del Frà Custoza 2016",
    "category": "Blancos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2016",
    "image": "",
    "price": 104,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "90-chamisal-chardonnay-2015",
    "sourceId": 90,
    "name": "Chamisal Chardonnay 2015",
    "category": "Blancos",
    "winery": "",
    "grape": "Chardonnay",
    "region": "",
    "country": "",
    "vintage": "2015",
    "image": "",
    "price": 194,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "91-domaine-de-montcy-cour-cheverny-2015",
    "sourceId": 91,
    "name": "Domaine de Montcy Cour-Cheverny 2015",
    "category": "Blancos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2015",
    "image": "",
    "price": 186,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "93-pine-ridge-dijon-clones-carneros-chardonnay-2013",
    "sourceId": 93,
    "name": "Pine Ridge Dijon Clones Carneros Chardonnay 2013",
    "category": "Blancos",
    "winery": "",
    "grape": "Chardonnay",
    "region": "",
    "country": "",
    "vintage": "2013",
    "image": "",
    "price": 242,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "94-puligny-montrachet-grand-vin-jacques-carillon-2013",
    "sourceId": 94,
    "name": "Puligny-Montrachet Grand Vin Jacques Carillon 2013",
    "category": "Blancos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2013",
    "image": "",
    "price": 586,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "95-pine-ridge-vineyards-chenin-blanc-viognier-white-blend-2017",
    "sourceId": 95,
    "name": "Pine Ridge Vineyards Chenin Blanc -Viognier White Blend 2017",
    "category": "Blancos",
    "winery": "",
    "grape": "Chenin Blanc",
    "region": "",
    "country": "",
    "vintage": "2017",
    "image": "",
    "price": 147,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "96-deloach-vineyards-chardonnay-2012",
    "sourceId": 96,
    "name": "DeLoach Vineyards Chardonnay 2012",
    "category": "Blancos",
    "winery": "",
    "grape": "Chardonnay",
    "region": "",
    "country": "",
    "vintage": "2012",
    "image": "",
    "price": 157,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "97-deloach-vineyards-ofs-chardonnay-2013",
    "sourceId": 97,
    "name": "DeLoach Vineyards OFS Chardonnay 2013",
    "category": "Blancos",
    "winery": "",
    "grape": "Chardonnay",
    "region": "",
    "country": "",
    "vintage": "2013",
    "image": "",
    "price": 259,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "98-de-loach-vineyards-ofs-chardonnay-2011",
    "sourceId": 98,
    "name": "De Loach vineyards OFS Chardonnay 2011",
    "category": "Blancos",
    "winery": "",
    "grape": "Chardonnay",
    "region": "",
    "country": "",
    "vintage": "2011",
    "image": "",
    "price": 259,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "99-la-grande-reserve-du-moulin-muscadet-de-sevre-et-maine-sur-lie-2017",
    "sourceId": 99,
    "name": "La Grande Réserve Du Moulin Muscadet de Sèvre et Maine Sur Lie 2017",
    "category": "Blancos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2017",
    "image": "",
    "price": 133,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "100-el-porvenir-laborum-torrontes-2021",
    "sourceId": 100,
    "name": "El Porvenir Laborum Torrontés 2021",
    "category": "Blancos",
    "winery": "",
    "grape": "Torrontés",
    "region": "",
    "country": "",
    "vintage": "2021",
    "image": "",
    "price": 87,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "101-il-pumo-chardonnay-igp-puglia-2022",
    "sourceId": 101,
    "name": "IL Pumo Chardonnay IGP Puglia 2022",
    "category": "Blancos",
    "winery": "",
    "grape": "Chardonnay",
    "region": "",
    "country": "",
    "vintage": "2022",
    "image": "",
    "price": 54,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "102-il-pumo-sauvignon-malvasia-igp-salento-2022",
    "sourceId": 102,
    "name": "IL Pumo Sauvignon-Malvasia IGP Salento 2022",
    "category": "Blancos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2022",
    "image": "",
    "price": 63,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "103-talo-verdeca-2022",
    "sourceId": 103,
    "name": "Talò Verdeca 2022",
    "category": "Blancos",
    "winery": "",
    "grape": "Verdeca",
    "region": "",
    "country": "",
    "vintage": "2022",
    "image": "",
    "price": 85,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "104-domodo-chardonnay-igp-puglia-2022",
    "sourceId": 104,
    "name": "Domodo Chardonnay IGP Puglia 2022",
    "category": "Blancos",
    "winery": "",
    "grape": "Chardonnay",
    "region": "",
    "country": "",
    "vintage": "2022",
    "image": "",
    "price": 43,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "105-domodo-pinot-grigio-igp-puglia-2022",
    "sourceId": 105,
    "name": "Domodo Pinot Grigio IGP Puglia 2022",
    "category": "Blancos",
    "winery": "",
    "grape": "Pinot Grigio",
    "region": "",
    "country": "",
    "vintage": "2022",
    "image": "",
    "price": 43,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "106-domodo-trebbiano-igp-puglia-2022",
    "sourceId": 106,
    "name": "Domodo Trebbiano IGP Puglia 2022",
    "category": "Blancos",
    "winery": "",
    "grape": "Trebbiano",
    "region": "",
    "country": "",
    "vintage": "2022",
    "image": "",
    "price": 43,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "107-barollo-frater-bianco-2022",
    "sourceId": 107,
    "name": "Barollo Frater Bianco 2022",
    "category": "Blancos",
    "winery": "",
    "grape": "",
    "region": "",
    "country": "",
    "vintage": "2022",
    "image": "",
    "price": 108,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "108-barollo-chardonnay-2019",
    "sourceId": 108,
    "name": "Barollo Chardonnay 2019",
    "category": "Blancos",
    "winery": "",
    "grape": "Chardonnay",
    "region": "",
    "country": "",
    "vintage": "2019",
    "image": "",
    "price": 223,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  },
  {
    "id": "109-cuvelier-los-andes-malbec-rose-2022",
    "sourceId": 109,
    "name": "Cuvelier Los Andes Malbec Rosé 2022",
    "category": "Rosados",
    "winery": "",
    "grape": "Malbec",
    "region": "",
    "country": "",
    "vintage": "2022",
    "image": "",
    "price": 150,
    "currency": "PEN",
    "status": "Consultar disponibilidad"
  }
];
